base_image = mcr.microsoft.com/devcontainers/base:ubuntu
features = rye miniforge zsh-common

ci: test-autogen test-scenarios test-global

test-autogen:
	@echo "Running autogen tests"
	devcontainer features test --skip-scenarios -i $(base_image) -f $(features)

test-global:
	@echo "Running global tests"
	devcontainer features test --global-scenarios-only -i $(base_image)

test-scenarios:
	@echo "Running scenario tests"
	devcontainer features test --skip-autogenerated --skip-duplicated -i $(base_image) -f $(features)
