#!/bin/bash

set -euo pipefail


DEVMODE=${DEVMODE:-false}
CHEZMOI_INSTALL_DIR=/usr/local/bin
CHEZMOI_PROFILE_SCRIPT=/etc/profile.d/chezmoi-dev-mode.sh
CHEZMOI_INSTALL_URL=get.chezmoi.io
CHEZMOI_INSTALLER_SCRIPT=


is_true() {
    case "${1}" in
        true|TRUE|True|1|yes|YES|on|ON)
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}


require_command() {
    local command_name=$1

    if ! command -v "${command_name}" >/dev/null 2>&1; then
        echo "Missing required command: ${command_name}"
        exit 1
    fi
}


install_chezmoi() {
    require_command curl
    mkdir -p "${CHEZMOI_INSTALL_DIR}"

    CHEZMOI_INSTALLER_SCRIPT=$(mktemp)

    echo "Downloading chezmoi installer..."
    curl -fsSL "${CHEZMOI_INSTALL_URL}" -o "${CHEZMOI_INSTALLER_SCRIPT}"

    echo "Installing chezmoi into ${CHEZMOI_INSTALL_DIR}..."
    sh "${CHEZMOI_INSTALLER_SCRIPT}" -b "${CHEZMOI_INSTALL_DIR}"
    rm -f "${CHEZMOI_INSTALLER_SCRIPT}"
    CHEZMOI_INSTALLER_SCRIPT=

    if [ ! -x "${CHEZMOI_INSTALL_DIR}/chezmoi" ]; then
        echo "chezmoi binary was not installed correctly."
        exit 1
    fi

    chown root:root "${CHEZMOI_INSTALL_DIR}/chezmoi"
    chmod 0755 "${CHEZMOI_INSTALL_DIR}/chezmoi"
}


configure_dev_mode() {
    if is_true "${DEVMODE}"; then
        cat > "${CHEZMOI_PROFILE_SCRIPT}" <<'EOF'
# Generated by the chezmoi dev container feature.
alias chezmoi='chezmoi --source .'
EOF
        chown root:root "${CHEZMOI_PROFILE_SCRIPT}"
        chmod 0644 "${CHEZMOI_PROFILE_SCRIPT}"
        echo "Enabled chezmoi development mode alias."
    else
        rm -f "${CHEZMOI_PROFILE_SCRIPT}"
        echo "chezmoi development mode alias is disabled."
    fi
}


echo "Activating feature 'chezmoi'"
trap 'rm -f "${CHEZMOI_INSTALLER_SCRIPT:-}"' EXIT
install_chezmoi
configure_dev_mode
echo "chezmoi installation complete."
